### ISSUE TITLE
[Suggestion] Option to blacklist biome fog for under lava

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Steveplays28/biome-fog#10]
If using this mod and going under lava it makes it a bit weird, and probably harder to navigate
![2023-05-01_03 53 45](https://user-images.githubusercontent.com/106651342/235425582-a5e773ab-cee9-4be3-99a1-dc9ca72caf99.png)
![2023-05-01_03 53 48](https://user-images.githubusercontent.com/106651342/235425590-8f814825-bf78-473c-9095-e2b779946dea.png)

**Comment by Steveplays28** [comment]
Ah, I forgot about lava and modded fluids. I thought the effect was kinda cool underwater.
I'll look into fixing this, thanks for the report!

**Comment by Aces-and-Jacks** [comment]
Well I like the effect with water, I just think the effect with lava is a bit weird

**Comment by Steveplays28** [comment]
Making progress on the fix, should be out soon. Sorry for the wait!

**Comment by Steveplays28** [comment]
I've fixed lava fog in the latest release, [`v1.1.0`](https://github.com/Steveplays28/biome-fog/releases/latest)!

Have fun!
