### ISSUE TITLE
Disable fog modification in superflat worlds

### ISSUE THREAD

**Issue by Felix14-v2** [Steveplays28/biome-fog#11]
In most cases superflat worlds are used as a creative testing ground, especially redstone-ready preset. And it is almost unusable with Biome Fog mod:
![image](https://user-images.githubusercontent.com/75726196/235432598-59ed4983-d25e-4a13-bdbb-76bc69823c2c.png)
16 chunks, btw

Currently I'm using Sodium Extra to disable the fog, but it is a bit inconvenient since you have to switch it each time after changing the world you are playing in. Maybe add a setting for this?

**Comment by Steveplays28** [comment]
Hadn't considered superflat worlds! I'll see if I can add a toggle per world (and a command to toggle so you don't have to change the config file manually).

**Comment by Felix14-v2** [comment]
Yea, a world blacklisting function would be a good solution

**Comment by Steveplays28** [comment]
I've added world blacklisting commands in the latest release, [`v1.1.0`](https://github.com/Steveplays28/biome-fog/releases/latest)!
It's saved to `/config/biome_fog/biome_fog_blacklisted_worlds.json`.

Have fun!
