### ISSUE TITLE
Crash when rendering Water Fog - 1.20

### ISSUE THREAD

**Issue by careeoki** [Steveplays28/biome-fog#19]
Entering water (deep enough to submerge player's head) instantly crashes my game. Very sad :(

Crash log:
[crash-2023-07-17_12.36.03-client.txt](https://github.com/Steveplays28/biome-fog/files/12072963/crash-2023-07-17_12.36.03-client.txt)

My mod list, if it's a compatibility error:

![](https://cdn.discordapp.com/attachments/747694378616881274/1130573151030485072/image.png)

Thank you! I really like the mod.

**Comment by Steveplays28** [comment]
I only reproduced this once in a large modpack I'm working on, but never got it again after.
Not sure what happens here but it seems like another mod touches the `world` variable in Minecraft's `BackgroundRenderer`, causing issues.

Could you rule out which mod is the issue via a [binary search](https://gist.github.com/TomeWyrm/a8cff19ce112edbc3c8a)?

**Comment by careeoki** [comment]
[crash-2023-07-22_10.41.51-client.txt](https://github.com/Steveplays28/biome-fog/files/12136857/crash-2023-07-22_10.41.51-client.txt)
I still get the same crash, even with just Biome Fog + Fabric API. I also tried updating to the latest Fabric API (the one listed on Biome Fog's download page) and Fabric loader version, but I get the same crash again.

**Comment by Steveplays28** [comment]
What does your `config/biome_fog` folder look like? Are the two config files `biome_fog.json` and `biome_fog_blacklisted_worlds.json` present?

**Comment by careeoki** [comment]
Both are present. I have not changed any configurations

**Comment by EthanRDoesMC** [comment]
Here to report the same issue, mostly different set of mods. 
[crash-2023-07-24_21.10.20-client.txt](https://github.com/Steveplays28/biome-fog/files/12156500/crash-2023-07-24_21.10.20-client.txt)

edit: Just wanted to add that I tried it with Quilt to the same effect

**Comment by Alomare** [comment]
Same here. Big mod list as well
[crash-2023-07-25_00.20.27-client.txt](https://github.com/Steveplays28/biome-fog/files/12156883/crash-2023-07-25_00.20.27-client.txt)

**Comment by Steveplays28** [comment]
Still haven't been able to reproduce this but I have a potential solution in mind, I'll let you guys know when I've gotten around to it and you can test it.

**Comment by Steveplays28** [comment]
Will release a hotfix later today! Thank you to @Leva25se for fixing this issue.

**Comment by Steveplays28** [comment]
The fix for this issue has been released in [`v1.1.1`](https://github.com/Steveplays28/biome-fog/releases/latest).
